/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewBingo;

import FabricaDeConexao.EfetuaConeccao;
import java.awt.Dimension;
import java.awt.Toolkit;
import static java.lang.Integer.parseInt;
import java.util.ArrayList;
import java.util.List;
import modelo.bean.CalculaDezenasMaisSorteadas;
import modelo.bean.Combinacoes;
import modelo.bean.CombinacoesDTO;
import modelo.bean.Dezenas;
import modelo.bean.GraficoDePontos;
import modelo.bean.GraficoDePontosPorPartes;
import modelo.bean.GraficoNivel;
import modelo.bean.GraficoPontosAnterioresPorPartes;
import modelo.bean.GraficoPontosDezenas;
import modelo.bean.GraficoPorPartes;
import modelo.bean.GraficoProbabilidadeNivel;
import modelo.bean.GraficoQuatorzePontos;
import modelo.bean.GraficoQuinzePontos;
import modelo.bean.Teste;
import modelo.bean.TotalDeCombinacoesQuinzePontos;
import modelos.dao.EscritordeQuinzePontos;
import modelos.dao.TotalProbabilidadeDAO;

/**
 *
 * @author ricar
 */
public class frmGraficos extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmGraficos
     */
    public frmGraficos() {
        initComponents();
        Dimension dimensao = Toolkit.getDefaultToolkit().getScreenSize();
        this.setBounds(((dimensao.width) - 1000) / 2,
                ((dimensao.height) - 1080) / 2,
                1000,
                950);
        this.setMaximizable(false);
        
        EfetuaConeccao efetuarconeccao = new EfetuaConeccao();
        efetuarconeccao.EfetuaConeccao();

        TotalProbabilidadeDAO totalprobabilidadedao1 = new TotalProbabilidadeDAO();
        CombinacoesDTO ultimosorteio = totalprobabilidadedao1.CombinacaoUltimoSorteio();
        txtUltimoSorteio.setText(ultimosorteio.getCombinacao());
        txtRefUltimoSorteio.setText(String.valueOf(ultimosorteio.getIdcombinacao()));
        txtIdUltimoSorteio.setText(ultimosorteio.getRefcombfifteen());
        txtQuinzePontos.setText(String.valueOf(ultimosorteio.getQtdfifteenpoints()));
        txtQuatorzePontos.setText(String.valueOf(ultimosorteio.getQtdeFourteenPoints()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dkpGraficos = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        txtIdFinalGraficoLinear = new javax.swing.JTextField();
        txtIdInicialGraficoLinear = new javax.swing.JTextField();
        btnGrafico14Pontos = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        txtIdFinall14pontos = new javax.swing.JTextField();
        txtIdInicial14pontos = new javax.swing.JTextField();
        btnGraficoLinear1 = new javax.swing.JButton();
        txtIdInicial15pontos = new javax.swing.JTextField();
        txtIdFinall15pontos = new javax.swing.JTextField();
        btnGrafico15Pontos = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        txtIdInicialPorPartes = new javax.swing.JTextField();
        txtIdFinalPorPartes = new javax.swing.JTextField();
        btnGraficoPorPartes = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        txtIdInicialDePontos = new javax.swing.JTextField();
        txtIdFinalDePontos = new javax.swing.JTextField();
        btnGraficoDePontos = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        txtIdInicialPorDezenas = new javax.swing.JTextField();
        txtIdFinalPorDezenas = new javax.swing.JTextField();
        btnGraficoPorDezenas = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        txtIdInicialProbabilidadeNivel = new javax.swing.JTextField();
        txtIdFinalProbabilidadeNivel = new javax.swing.JTextField();
        btnGraficoProbabilidadeNivel = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        txtIdInicialDePontosPorPartes = new javax.swing.JTextField();
        txtIdFinalDePontosPorPartes = new javax.swing.JTextField();
        btnGraficoProbabilidadeNivel1 = new javax.swing.JButton();
        txtIdInicialDePontosAnteriores = new javax.swing.JTextField();
        txtIdFinalDePontosAnteriores = new javax.swing.JTextField();
        btnGraficoPontosAnteriores = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JSeparator();
        btnGraficoAposta = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        txtUltimoSorteio = new javax.swing.JTextField();
        txtIdUltimoSorteio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtRefUltimoSorteio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtQuinzePontos = new javax.swing.JTextField();
        txtQuatorzePontos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-editar-relatório-gráfico-24.png"))); // NOI18N

        dkpGraficos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtIdInicialGraficoLinear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdInicialGraficoLinearActionPerformed(evt);
            }
        });

        btnGrafico14Pontos.setText("Gráfico 14 pontos");
        btnGrafico14Pontos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrafico14PontosActionPerformed(evt);
            }
        });

        btnGraficoLinear1.setText("Gráfico Linear");
        btnGraficoLinear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficoLinear1ActionPerformed(evt);
            }
        });

        btnGrafico15Pontos.setText("Gráfico 15 pontos");
        btnGrafico15Pontos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrafico15PontosActionPerformed(evt);
            }
        });

        btnGraficoPorPartes.setText("Gráfico por partes");
        btnGraficoPorPartes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficoPorPartesActionPerformed(evt);
            }
        });

        btnGraficoDePontos.setText("Gráfico de Pontos");
        btnGraficoDePontos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficoDePontosActionPerformed(evt);
            }
        });

        btnGraficoPorDezenas.setText("Gráfico por Dezenas");
        btnGraficoPorDezenas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficoPorDezenasActionPerformed(evt);
            }
        });

        btnGraficoProbabilidadeNivel.setText("Gráfico probabilidade");
        btnGraficoProbabilidadeNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficoProbabilidadeNivelActionPerformed(evt);
            }
        });

        txtIdInicialDePontosPorPartes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdInicialDePontosPorPartesActionPerformed(evt);
            }
        });

        btnGraficoProbabilidadeNivel1.setText("Gráfico Pontos Por Partes");
        btnGraficoProbabilidadeNivel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficoProbabilidadeNivel1ActionPerformed(evt);
            }
        });

        txtIdInicialDePontosAnteriores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdInicialDePontosAnterioresActionPerformed(evt);
            }
        });

        btnGraficoPontosAnteriores.setText("Gráfico Pontos anteriores");
        btnGraficoPontosAnteriores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficoPontosAnterioresActionPerformed(evt);
            }
        });

        btnGraficoAposta.setText("Gráfico aposta");
        btnGraficoAposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficoApostaActionPerformed(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Pegar os últimos 75 sorteios");

        javax.swing.GroupLayout dkpGraficosLayout = new javax.swing.GroupLayout(dkpGraficos);
        dkpGraficos.setLayout(dkpGraficosLayout);
        dkpGraficosLayout.setHorizontalGroup(
            dkpGraficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dkpGraficosLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(txtIdInicialGraficoLinear, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtIdFinalGraficoLinear, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGraficoLinear1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addGroup(dkpGraficosLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(txtIdInicial14pontos, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtIdFinall14pontos, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGrafico14Pontos, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
            .addGroup(dkpGraficosLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(txtIdInicial15pontos, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtIdFinall15pontos, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGrafico15Pontos, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
            .addGroup(dkpGraficosLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(txtIdInicialPorPartes, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtIdFinalPorPartes, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGraficoPorPartes, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
            .addGroup(dkpGraficosLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(txtIdInicialDePontos, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtIdFinalDePontos, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGraficoDePontos, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addGroup(dkpGraficosLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(txtIdInicialPorDezenas, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtIdFinalPorDezenas, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGraficoPorDezenas, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
            .addGroup(dkpGraficosLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(txtIdInicialProbabilidadeNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtIdFinalProbabilidadeNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField1)
                .addGap(18, 18, 18)
                .addComponent(btnGraficoProbabilidadeNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dkpGraficosLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(dkpGraficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dkpGraficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(dkpGraficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator3))
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(dkpGraficosLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(dkpGraficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtIdInicialDePontosAnteriores, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdInicialDePontosPorPartes, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dkpGraficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdFinalDePontosPorPartes, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdFinalDePontosAnteriores, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGraficoAposta, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dkpGraficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGraficoProbabilidadeNivel1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGraficoPontosAnteriores, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
            .addGroup(dkpGraficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dkpGraficosLayout.createSequentialGroup()
                    .addContainerGap(30, Short.MAX_VALUE)
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)))
        );
        dkpGraficosLayout.setVerticalGroup(
            dkpGraficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dkpGraficosLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(dkpGraficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdInicialGraficoLinear, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdFinalGraficoLinear, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGraficoLinear1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(dkpGraficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdInicial14pontos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdFinall14pontos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrafico14Pontos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(dkpGraficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdInicial15pontos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdFinall15pontos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrafico15Pontos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(dkpGraficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdInicialPorPartes, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdFinalPorPartes, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGraficoPorPartes, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(dkpGraficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdInicialDePontos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdFinalDePontos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGraficoDePontos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(dkpGraficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdInicialPorDezenas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdFinalPorDezenas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGraficoPorDezenas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(dkpGraficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdInicialProbabilidadeNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdFinalProbabilidadeNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGraficoProbabilidadeNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(dkpGraficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdInicialDePontosPorPartes, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdFinalDePontosPorPartes, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGraficoProbabilidadeNivel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(dkpGraficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdInicialDePontosAnteriores, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdFinalDePontosAnteriores, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGraficoPontosAnteriores, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGraficoAposta, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(dkpGraficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dkpGraficosLayout.createSequentialGroup()
                    .addContainerGap(535, Short.MAX_VALUE)
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(132, 132, 132)))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gráficos");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        txtUltimoSorteio.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtIdUltimoSorteio.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setText("Último sorteio ->");

        jLabel3.setText("Id:");

        jLabel4.setText("Combinação:");

        txtRefUltimoSorteio.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel5.setText("Ref:");

        txtQuinzePontos.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtQuatorzePontos.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel6.setText("15 pontos");

        jLabel7.setText("14 pontos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(342, 342, 342)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(dkpGraficos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtQuinzePontos, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtQuatorzePontos, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSair)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdUltimoSorteio, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRefUltimoSorteio, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUltimoSorteio, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(dkpGraficos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSair)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUltimoSorteio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(txtRefUltimoSorteio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txtIdUltimoSorteio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtQuatorzePontos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txtQuinzePontos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(42, 42, 42))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGraficoLinear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficoLinear1ActionPerformed
        GraficoNivel graficonivel = new GraficoNivel();
        graficonivel.GraficoNivel(parseInt(txtIdInicialGraficoLinear.getText()), parseInt(txtIdFinalGraficoLinear.getText()));
    }//GEN-LAST:event_btnGraficoLinear1ActionPerformed

    private void txtIdInicialGraficoLinearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdInicialGraficoLinearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdInicialGraficoLinearActionPerformed

    private void btnGrafico15PontosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrafico15PontosActionPerformed
       GraficoQuinzePontos graficoquinzepontos = new GraficoQuinzePontos();
        graficoquinzepontos.GraficoQuinzePontos(parseInt(txtIdInicial15pontos.getText()), parseInt(txtIdFinall15pontos.getText()));
    }//GEN-LAST:event_btnGrafico15PontosActionPerformed

    private void btnGraficoPorPartesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficoPorPartesActionPerformed
        GraficoPorPartes graficoporpartes = new GraficoPorPartes();
        graficoporpartes.GraficoPorPartes(parseInt(txtIdInicialPorPartes.getText()), parseInt(txtIdFinalPorPartes.getText()));
    }//GEN-LAST:event_btnGraficoPorPartesActionPerformed

    private void btnGraficoDePontosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficoDePontosActionPerformed
       GraficoDePontos graficodepontos = new GraficoDePontos();
        graficodepontos.GraficoDePontos(parseInt(txtIdInicialDePontos.getText()), parseInt(txtIdFinalDePontos.getText()));
    }//GEN-LAST:event_btnGraficoDePontosActionPerformed

    private void btnGraficoPorDezenasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficoPorDezenasActionPerformed
        EfetuaConeccao efetuarconeccao = new EfetuaConeccao();
        efetuarconeccao.EfetuaConeccao();
        GraficoPontosDezenas graficoPontosDezenas = new GraficoPontosDezenas();
        graficoPontosDezenas.GraficoPontosDezenas(Integer.parseInt(txtIdInicialPorDezenas.getText()), Integer.parseInt(txtIdFinalPorDezenas.getText()));        // TODO add your handling code here:
    }//GEN-LAST:event_btnGraficoPorDezenasActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnGrafico14PontosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrafico14PontosActionPerformed
        GraficoQuatorzePontos graficoquatorzepontos = new GraficoQuatorzePontos();
        graficoquatorzepontos.GraficoQuatorzePontos(parseInt(txtIdInicial14pontos.getText()), parseInt(txtIdFinall14pontos.getText()));
    }//GEN-LAST:event_btnGrafico14PontosActionPerformed

    private void btnGraficoProbabilidadeNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficoProbabilidadeNivelActionPerformed
       
        EfetuaConeccao efetuarconeccao = new EfetuaConeccao();
        efetuarconeccao.EfetuaConeccao();
        
        GraficoProbabilidadeNivel probabilidadeNivel = new GraficoProbabilidadeNivel();
        probabilidadeNivel.GraficoProbabilidadeNivel(txtUltimoSorteio.getText(), 
                Integer.parseInt(txtIdInicialProbabilidadeNivel.getText()), Integer.parseInt(txtIdFinalProbabilidadeNivel.getText()));
    }//GEN-LAST:event_btnGraficoProbabilidadeNivelActionPerformed

    private void btnGraficoProbabilidadeNivel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficoProbabilidadeNivel1ActionPerformed
        GraficoDePontosPorPartes graficodepontos = new GraficoDePontosPorPartes();
        graficodepontos.GraficoDePontosPorPartes(parseInt(txtIdInicialDePontosPorPartes.getText()), parseInt(txtIdFinalDePontosPorPartes.getText()));
    }//GEN-LAST:event_btnGraficoProbabilidadeNivel1ActionPerformed

    private void txtIdInicialDePontosPorPartesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdInicialDePontosPorPartesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdInicialDePontosPorPartesActionPerformed

    private void txtIdInicialDePontosAnterioresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdInicialDePontosAnterioresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdInicialDePontosAnterioresActionPerformed

    private void btnGraficoPontosAnterioresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficoPontosAnterioresActionPerformed
        GraficoPontosAnterioresPorPartes graficodepontosanteriores = new GraficoPontosAnterioresPorPartes();
        graficodepontosanteriores.GraficoDePontosAnterioresPorPartes(parseInt(txtIdInicialDePontosAnteriores.getText()), parseInt(txtIdFinalDePontosAnteriores.getText()));
    }//GEN-LAST:event_btnGraficoPontosAnterioresActionPerformed

    private void btnGraficoApostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficoApostaActionPerformed
        GraficoPontosAnterioresPorPartes graficodepontosanteriores = new GraficoPontosAnterioresPorPartes();
        graficodepontosanteriores.GraficoDePontosAnterioresPorPartes(parseInt(txtIdInicialDePontosAnteriores.getText()), parseInt(txtIdFinalDePontosAnteriores.getText()), txtUltimoSorteio.getText());
    }//GEN-LAST:event_btnGraficoApostaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGrafico14Pontos;
    private javax.swing.JButton btnGrafico15Pontos;
    private javax.swing.JButton btnGraficoAposta;
    private javax.swing.JButton btnGraficoDePontos;
    private javax.swing.JButton btnGraficoLinear1;
    private javax.swing.JButton btnGraficoPontosAnteriores;
    private javax.swing.JButton btnGraficoPorDezenas;
    private javax.swing.JButton btnGraficoPorPartes;
    private javax.swing.JButton btnGraficoProbabilidadeNivel;
    private javax.swing.JButton btnGraficoProbabilidadeNivel1;
    private javax.swing.JButton btnSair;
    public static javax.swing.JPanel dkpGraficos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtIdFinalDePontos;
    private javax.swing.JTextField txtIdFinalDePontosAnteriores;
    private javax.swing.JTextField txtIdFinalDePontosPorPartes;
    private javax.swing.JTextField txtIdFinalGraficoLinear;
    private javax.swing.JTextField txtIdFinalPorDezenas;
    private javax.swing.JTextField txtIdFinalPorPartes;
    private javax.swing.JTextField txtIdFinalProbabilidadeNivel;
    private javax.swing.JTextField txtIdFinall14pontos;
    private javax.swing.JTextField txtIdFinall15pontos;
    private javax.swing.JTextField txtIdInicial14pontos;
    private javax.swing.JTextField txtIdInicial15pontos;
    private javax.swing.JTextField txtIdInicialDePontos;
    private javax.swing.JTextField txtIdInicialDePontosAnteriores;
    private javax.swing.JTextField txtIdInicialDePontosPorPartes;
    private javax.swing.JTextField txtIdInicialGraficoLinear;
    private javax.swing.JTextField txtIdInicialPorDezenas;
    private javax.swing.JTextField txtIdInicialPorPartes;
    private javax.swing.JTextField txtIdInicialProbabilidadeNivel;
    private javax.swing.JTextField txtIdUltimoSorteio;
    private javax.swing.JTextField txtQuatorzePontos;
    private javax.swing.JTextField txtQuinzePontos;
    private javax.swing.JTextField txtRefUltimoSorteio;
    private javax.swing.JTextField txtUltimoSorteio;
    // End of variables declaration//GEN-END:variables
}
